module.exports = grammar({
  name: 'tss',

  extras: $ => [$.comment, /[ \t]/, $.newline],

  rules: {
    s: $ => repeat($.hl_rule),
    hl_rule: $ => seq(
        field('selectors', $.selectors),
        ':',
        field('style', choice($.highlight, $.properties)),
        ';'
    ),
    comment: $ => /#.*/,
    newline: $ => /\r?\n/,

    selectors: $ => seq($.selector, repeat(seq(',', $.selector))),
    selector: $ => repeat1($.sel_symbol),
    sel_symbol: $ => choice(
        $.sel_kind,
        $.sel_twins,
        $.sel_siblings,
        $.sel_child,
    ),
    sel_kind: $ => /[a-z][0-9a-zA-Z-_]+/,
    sel_twins: $ => prec.left(2, seq($.sel_symbol, '+', $.sel_symbol)),
    sel_siblings: $ => prec.left(2, seq($.sel_symbol, '~', $.sel_symbol)),
    sel_child: $ => prec.left(2, seq($.sel_symbol, '>', $.sel_symbol)),

    properties: $ => seq(
        '{',
        field('properties', repeat(seq(field('property', $.property), ','))),
        '}'
    ),
    property: $ => choice(
        field('fg', $.fg),
        field('bg', $.bg),
        field('attr', $.attrb),
        field('attribute', $.attribute)
    ),
    fg: $ => seq('fg', ':', choice($.rgb_color, $.ansi_color, $.color_name)),
    bg: $ => seq('bg', ':', choice($.rgb_color, $.ansi_color, $.color_name)),
    attrb: $ => seq('attr', ':', repeat($.attrs)),
    attribute: $ => seq('attribute', ':', repeat($.attrs)),
    attrs : $ => seq($.attr, repeat($.attr_or)),
    attr_or: $ => seq('|', $.attr),
    attr: $ => choice(
        'bold',
        'italic',
        'underlined',
        'underline',
        'reverse',
    ),

    rgb_color: $ => /#[0-9a-fA-F]{6}/,
    ansi_color: $ => choice(
        field('ansi_color_dec', /[0-9]+/),
        field('ansi_color_hex', /0x[0-9a-fA-F]+/),
    ),
    color_name: $ => choice(
        'black',
        'darkgrey',
        'dark-grey',
        'dark_grey',
        'red',
        'darkred',
        'dark-red',
        'dark_red',
        'green',
        'darkgreen',
        'dark-green',
        'dark_green',
        'yellow',
        'darkyellow',
        'dark-yellow',
        'dark_yellow',
        'blue',
        'darkblue',
        'dark-blue',
        'dark_blue',
        'magenta',
        'darkmagenta',
        'dark-magenta',
        'dark_magenta',
        'cyan',
        'darkcyan',
        'dark-cyan',
        'dark_cyan',
        'white',
        'grey',
        'bg-canvas',
        'fg-canvas',
    ),
    highlight: $ => choice(
        'canvas',
        'comment',
        'constant',
        'string',
        'char',
        'number',
        'boolean',
        'float',
        'identifier',
        'function',
        'statement',
        'conditional',
        'repeat',
        'label',
        'operator',
        'keyword',
        'exception',
        'preproc',
        'include',
        'define',
        'macro',
        'precondit',
        'type',
        'storage-class',
        'structure',
        'typedef',
        'special',
        'special-char',
        'tag',
        'delimiter',
        'special-comment',
        'debug',
        'underlined',
        'ignore',
        'error',
        'todo',
        'line-nr',
        'prompt',
        'status-line',
        'tab-line',
        'tab-option',
        'tab-select'
    )
  }
});

